apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lunar.fullname" . }}-operator
  namespace: {{ include "lunar.snippetNamespace" . }}
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lunar.fullname" . }}-operator
  namespace: {{ include "lunar.snippetNamespace" . }}
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
subjects:
  - kind: ServiceAccount
    name: {{ include "lunar.fullname" . }}-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "lunar.fullname" . }}-operator
  apiGroup: rbac.authorization.k8s.io
