apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lunar.fullname" . }}-snippet-pod
  namespace: {{ include "lunar.snippetNamespace" . }}
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
    app.kubernetes.io/component: snippet-pod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lunar.fullname" . }}-snippet-pod
  namespace: {{ include "lunar.snippetNamespace" . }}
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
    app.kubernetes.io/component: snippet-pod
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lunar.fullname" . }}-snippet-pod
  namespace: {{ include "lunar.snippetNamespace" . }}
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
    app.kubernetes.io/component: snippet-pod
subjects:
  - kind: ServiceAccount
    name: {{ include "lunar.fullname" . }}-snippet-pod
    namespace: {{ include "lunar.snippetNamespace" . }}
roleRef:
  kind: Role
  name: {{ include "lunar.fullname" . }}-snippet-pod
  apiGroup: rbac.authorization.k8s.io
